name: efood_multivendor
description: A new Flutter application.
publish_to: "none"
version: 2.9.2+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.3.0
  country_code_picker: ^2.0.2
  crypto: ^3.0.2
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_text_style: ^2.7.2
  geolocator: ^8.2.1
  get: ^4.6.5
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  google_sign_in: ^5.2.1
  http: ^0.13.4
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pointer_interceptor: ^0.9.0+1
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  url_launcher: ^6.0.17
  url_strategy: ^0.2.0
  device_preview: ^1.1.0
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
          weight: 400
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
