name: fasteriy
description: a multi-vendor food and groceries mobile application with fast
  delivery service.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.3.0
  country_code_picker: ^2.0.2
  crypto: ^3.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  equatable: ^2.0.5
  extended_image: ^6.2.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^15.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.6.2
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_text_style: ^2.7.2
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.4.0+3
  google_sign_in: ^5.2.1
  http: ^1.1.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  phone_number: ^1.0.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pointer_interceptor: ^0.9.0+1
  provider: ^6.0.3
  rename: ^2.0.1
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  universal_html: ^2.0.8
  url_launcher: ^6.0.17
  url_strategy: ^0.2.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
          weight: 400
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
